(() => {
  const records = [
    {
      id:"my01-my02-functional-dyspepsia", area:"Gastrointestinal", genus:"Weizmannia + Bacillus", species:"coagulans + subtilis", strain:"MY01 + MY02", former:"Antes: Bacillus coagulans MY01 + Bacillus subtilis MY02", displayName:"<i>Weizmannia coagulans</i> MY01 + <i>Bacillus subtilis</i> MY02", aliases:["MY01","MY02","DuoSpore","dispepsia funcional"], condition:"Dispepsia funcional", conditionShort:"Dispepsia funcional", keywords:["dispepsia","plenitud","saciedad temprana","dolor epigástrico"], intent:"Tratamiento", ageGroup:"adult", mexicoAvailable:true, interventionType:"Combinación inseparable de dos cepas esporuladas",
      effect:"Un ensayo aleatorizado evaluó la combinación MY01 + MY02 en adultos con dispepsia funcional durante ocho semanas.", outcome:"Respuesta clínica y síntomas de dispepsia", metric:"ECA de 68 participantes", absolute:"2.5 × 10⁹ UFC por cápsula, dos veces al día", nnt:"No publicado", dose:"5 × 10⁹ UFC/día", doseDetail:"El ensayo administró una cápsula con 2.5 × 10⁹ UFC dos veces al día. Otros componentes de productos comerciales no forman parte de esta relación clínica.", duration:"8 semanas", population:"Adultos con dispepsia funcional.", caveat:"La relación corresponde a la combinación MY01 + MY02 estudiada. No se extrapola a otras cepas de W. coagulans o B. subtilis.", studies:[{design:"ECA doble ciego",n:"68",year:"2021",result:"Mayor proporción de respuesta clínica y cambios en síntomas frente a placebo.",limitation:"Un ensayo; formulación y pauta específicas.",url:"https://pubmed.ncbi.nlm.nih.gov/34358486/"}],
      en:{condition:"Functional dyspepsia",conditionShort:"Functional dyspepsia",interventionType:"Inseparable two-strain spore-forming combination",effect:"A randomized trial evaluated MY01 + MY02 in adults with functional dyspepsia for eight weeks.",outcome:"Clinical response and dyspepsia symptoms",metric:"68-participant RCT",absolute:"2.5 × 10⁹ CFU per capsule twice daily",nnt:"Not reported",dose:"5 × 10⁹ CFU/day",doseDetail:"The trial administered one capsule containing 2.5 × 10⁹ CFU twice daily. Other commercial-product components are not part of this clinical relation.",duration:"8 weeks",population:"Adults with functional dyspepsia.",caveat:"This relation applies to the studied MY01 + MY02 combination and is not extrapolated to other W. coagulans or B. subtilis strains.",studies:[{design:"Double-blind RCT",n:"68",year:"2021",result:"A higher clinical-response proportion and symptom changes were reported versus placebo.",limitation:"One trial with a specific formulation and regimen.",url:"https://pubmed.ncbi.nlm.nih.gov/34358486/"}]}
    },
    {
      id:"lp-dr7-urti", area:"Alergología e inmunología", genus:"Lactiplantibacillus", species:"plantarum", strain:"DR7", former:"Antes: Lactobacillus plantarum DR7", aliases:["DR7","infección respiratoria","URTI"], condition:"Frecuencia y duración de síntomas de infección respiratoria alta", conditionShort:"Infección respiratoria alta", keywords:["resfriado","infección respiratoria","síntomas nasales","URTI"], intent:"Prevención", ageGroup:"adult", mexicoAvailable:true, interventionType:"Microorganismo vivo",
      effect:"Un ensayo aleatorizado registró la frecuencia de infecciones respiratorias altas y la duración de síntomas nasales durante doce semanas.", outcome:"Frecuencia de infección y duración de síntomas nasales", metric:"Duración: diferencia media 5.09 días (IC 95% 0.42–9.75)", absolute:"Frecuencia: diferencia media 0.32 episodios (IC 95% 0.01–0.63)", nnt:"No publicado", dose:"1 × 10⁹ UFC/día", doseDetail:"Administración diaria de DR7 durante doce semanas.", duration:"12 semanas", population:"Adultos sanos de 18 a 60 años.", caveat:"Los desenlaces fueron episodios y síntomas autorreportados; no equivale a tratamiento de una infección establecida.", studies:[{design:"ECA doble ciego",n:"109",year:"2019",result:"Menor duración de síntomas nasales y menor frecuencia de infecciones respiratorias altas frente a placebo.",limitation:"Un ensayo y desenlaces autorreportados.",url:"https://pubmed.ncbi.nlm.nih.gov/30954261/"}],
      en:{condition:"Frequency and duration of upper-respiratory symptoms",conditionShort:"Upper respiratory infection",interventionType:"Live microorganism",effect:"A randomized trial recorded upper-respiratory infection frequency and nasal-symptom duration over twelve weeks.",outcome:"Infection frequency and nasal-symptom duration",metric:"Duration: mean difference 5.09 days (95% CI 0.42–9.75)",absolute:"Frequency: mean difference 0.32 episodes (95% CI 0.01–0.63)",nnt:"Not reported",dose:"1 × 10⁹ CFU/day",doseDetail:"Daily DR7 administration for twelve weeks.",duration:"12 weeks",population:"Healthy adults aged 18–60 years.",caveat:"Outcomes were self-reported episodes and symptoms; this is not treatment of an established infection.",studies:[{design:"Double-blind RCT",n:"109",year:"2019",result:"Shorter nasal-symptom duration and fewer upper-respiratory infections were reported versus placebo.",limitation:"One trial with self-reported outcomes.",url:"https://pubmed.ncbi.nlm.nih.gov/30954261/"}]}
    },
    {
      id:"i3799-pediatric-acute-diarrhea", area:"Pediatría", genus:"Saccharomyces", species:"boulardii", strain:"CNCM I-3799", kind:"yeast", aliases:["CNCM I-3799","S. boulardii I-3799","diarrea aguda"], condition:"Diarrea aguda en menores de 36 meses", conditionShort:"Diarrea aguda · I-3799", keywords:["pediatría","diarrea aguda","gastroenteritis"], intent:"Coadyuvante", ageGroup:"pediatric", mexicoAvailable:true, interventionType:"Levadura viva",
      effect:"Un ensayo aleatorizado evaluó CNCM I-3799 junto con la atención habitual en lactantes y niños pequeños con diarrea aguda.", outcome:"Duración y gravedad de la diarrea", metric:"ECA de 100 participantes", absolute:"Menor duración y gravedad reportadas", nnt:"No publicado", dose:"Pauta del ensayo", doseDetail:"La dosis debe confirmarse en el texto completo antes de trasladarla a una ficha posológica.", duration:"Durante el episodio agudo", population:"Lactantes y niños menores de 36 meses con diarrea aguda.", caveat:"No sustituye rehidratación oral ni evaluación de deshidratación o signos de alarma. No es intercambiable con CNCM I-745.", studies:[{design:"ECA doble ciego",n:"100",year:"2020",result:"Menor duración y gravedad de la diarrea frente al grupo de comparación.",limitation:"Un ensayo; población menor de 36 meses.",url:"https://pubmed.ncbi.nlm.nih.gov/32796401/"}],
      en:{condition:"Acute diarrhea in children younger than 36 months",conditionShort:"Acute diarrhea · I-3799",interventionType:"Live yeast",effect:"A randomized trial evaluated CNCM I-3799 with usual care in infants and young children with acute diarrhea.",outcome:"Diarrhea duration and severity",metric:"100-participant RCT",absolute:"Shorter duration and lower severity were reported",nnt:"Not reported",dose:"Trial regimen",doseDetail:"The dose requires full-text confirmation before transfer to a dosing field.",duration:"During the acute episode",population:"Infants and children younger than 36 months with acute diarrhea.",caveat:"It does not replace oral rehydration or assessment for dehydration and warning signs. It is not interchangeable with CNCM I-745.",studies:[{design:"Double-blind RCT",n:"100",year:"2020",result:"Shorter diarrhea duration and lower severity were reported versus the comparison group.",limitation:"One trial in children younger than 36 months.",url:"https://pubmed.ncbi.nlm.nih.gov/32796401/"}]}
    },
    {
      id:"i31-ibs", area:"Gastrointestinal", genus:"Formulación", species:"i3.1", strain:"CECT 7483 + CECT 7484 + CECT 7485", displayName:"<i>Pediococcus acidilactici</i> CECT 7483 + <i>Lactiplantibacillus plantarum</i> CECT 7484/7485", aliases:["i3.1","CECT 7483","CECT 7484","CECT 7485","SII"], condition:"Síndrome de intestino irritable", conditionShort:"SII · formulación i3.1", keywords:["SII","IBS","calidad de vida","dolor","consistencia fecal"], intent:"Tratamiento", ageGroup:"adult", mexicoAvailable:true, interventionType:"Combinación inseparable de tres cepas",
      effect:"Ensayos controlados evaluaron la combinación de tres cepas en adultos con síndrome de intestino irritable.", outcome:"Calidad de vida, dolor y consistencia fecal", metric:"Respuesta IBS-QoL ≥15 puntos: 55% vs 17%", absolute:"Diferencia de 38 puntos porcentuales en el primer ECA", nnt:"≈3; cálculo a partir del primer ECA", dose:"3 × 10⁹ UFC/día", doseDetail:"Una dosis diaria con 1 × 10⁹ UFC de cada cepa durante seis semanas en el primer ensayo.", duration:"6 semanas", population:"Adultos con síndrome de intestino irritable.", caveat:"La relación corresponde a las tres cepas administradas juntas. Una formulación que añada vitamina D constituye una intervención diferente.", studies:[{design:"ECA doble ciego",n:"84",year:"2014",result:"Mayor proporción con mejoría ≥15 puntos en IBS-QoL: 55% frente a 17%.",limitation:"Duración de seis semanas y combinación inseparable.",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC4093724/"},{design:"ECA piloto mexicano",n:"55",year:"2021",result:"Mayor respuesta de calidad de vida, dolor y consistencia fecal en los grupos con probiótico.",limitation:"Muestra pequeña y brazo con cointervención antiespasmódica.",url:"https://karger.com/ddi/article-abstract/39/3/294/102931"}],
      en:{condition:"Irritable bowel syndrome",conditionShort:"IBS · i3.1 formulation",interventionType:"Inseparable three-strain combination",effect:"Controlled trials evaluated the three-strain combination in adults with irritable bowel syndrome.",outcome:"Quality of life, pain, and stool consistency",metric:"IBS-QoL ≥15-point response: 55% vs 17%",absolute:"38-percentage-point difference in the first RCT",nnt:"≈3; calculated from the first RCT",dose:"3 × 10⁹ CFU/day",doseDetail:"One daily dose containing 1 × 10⁹ CFU of each strain for six weeks in the first trial.",duration:"6 weeks",population:"Adults with irritable bowel syndrome.",caveat:"This relation applies to the three strains administered together. A formulation adding vitamin D is a different intervention.",studies:[{design:"Double-blind RCT",n:"84",year:"2014",result:"A higher proportion achieved a ≥15-point IBS-QoL improvement: 55% versus 17%.",limitation:"Six-week duration and inseparable combination.",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC4093724/"},{design:"Mexican pilot RCT",n:"55",year:"2021",result:"Higher quality-of-life, pain, and stool-consistency response rates were reported in probiotic groups.",limitation:"Small sample and one antispasmodic co-intervention arm.",url:"https://karger.com/ddi/article-abstract/39/3/294/102931"}]}
    },
    {
      id:"ncfm-bi07-bloating", area:"Gastrointestinal", genus:"Lactobacillus acidophilus + Bifidobacterium animalis", species:"acidophilus + subsp. lactis", strain:"NCFM + Bi-07", displayName:"<i>Lactobacillus acidophilus</i> NCFM + <i>Bifidobacterium animalis</i> subsp. <i>lactis</i> Bi-07", aliases:["NCFM","Bi-07","distensión","bloating"], condition:"Distensión abdominal en trastornos intestinales funcionales", conditionShort:"Distensión abdominal", keywords:["distensión","hinchazón","trastorno intestinal funcional"], intent:"Tratamiento", ageGroup:"adult", mexicoAvailable:true, interventionType:"Combinación de dos cepas",
      effect:"Un ensayo aleatorizado evaluó NCFM + Bi-07 en adultos con trastornos intestinales funcionales y distensión abdominal.", outcome:"Puntuación de distensión abdominal", metric:"Semana 4: 4.10 vs 6.17; p=0.009", absolute:"Cambio de gravedad favoreció la combinación; p<0.01", nnt:"No publicado", dose:"2 × 10¹¹ UFC/día", doseDetail:"La formulación estudiada aportó 1 × 10¹¹ UFC de cada cepa al día.", duration:"8 semanas", population:"Adultos con trastorno intestinal funcional sin estreñimiento.", caveat:"El resultado pertenece a NCFM + Bi-07; productos con cepas adicionales no reproducen necesariamente la intervención.", studies:[{design:"ECA doble ciego",n:"60",year:"2011",result:"Menor puntuación de distensión en la semana 4: 4.10 frente a 6.17.",limitation:"Muestra pequeña; el contraste de la semana 8 fue menos preciso.",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3033537/"}],
      en:{condition:"Abdominal bloating in functional bowel disorders",conditionShort:"Abdominal bloating",interventionType:"Two-strain combination",effect:"A randomized trial evaluated NCFM + Bi-07 in adults with functional bowel disorders and bloating.",outcome:"Abdominal-bloating score",metric:"Week 4: 4.10 vs 6.17; p=0.009",absolute:"Severity change favored the combination; p<0.01",nnt:"Not reported",dose:"2 × 10¹¹ CFU/day",doseDetail:"The studied formulation provided 1 × 10¹¹ CFU of each strain per day.",duration:"8 weeks",population:"Adults with a non-constipation functional bowel disorder.",caveat:"The result belongs to NCFM + Bi-07; products containing additional strains do not necessarily reproduce the intervention.",studies:[{design:"Double-blind RCT",n:"60",year:"2011",result:"A lower bloating score was reported at week 4: 4.10 versus 6.17.",limitation:"Small sample; the week-8 contrast was less precise.",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3033537/"}]}
    },
    {
      id:"bpl1-live-adiposity", area:"Metabolismo y composición corporal", genus:"Bifidobacterium animalis", species:"subsp. lactis", strain:"CECT 8145 viva", aliases:["BPL1","CECT 8145","BPL-1 viva"], condition:"Marcadores antropométricos en obesidad abdominal", conditionShort:"Obesidad abdominal · BPL1 viva", keywords:["obesidad","adiposidad","cintura","IMC","BPL1"], intent:"Coadyuvante", ageGroup:"adult", mexicoAvailable:true, interventionType:"Microorganismo vivo; distinto de BPL1-HT",
      effect:"Un ensayo de tres brazos comparó CECT 8145 viva, la preparación inactivada y placebo durante tres meses.", outcome:"IMC, cintura y área de grasa visceral", metric:"1 × 10¹⁰ UFC/día; n=135", absolute:"Los contrastes frente a placebo variaron entre la forma viva e inactivada", nnt:"No aplica", dose:"1 × 10¹⁰ UFC/día", doseDetail:"Una cápsula diaria durante tres meses. La forma viva y la inactivada se registran como intervenciones separadas.", duration:"12 semanas", population:"Adultos con obesidad abdominal.", caveat:"Los desenlaces fueron antropométricos y no equivalen a reducción de eventos clínicos ni a tratamiento único de obesidad.", studies:[{design:"ECA doble ciego de 3 brazos",n:"135",year:"2019",result:"Menor IMC frente a placebo con la forma viva; otros cambios variaron por forma y sexo.",limitation:"Análisis múltiples, desenlaces antropométricos y vínculos industriales declarados.",url:"https://pubmed.ncbi.nlm.nih.gov/30262813/"}],
      en:{condition:"Anthropometric markers in abdominal obesity",conditionShort:"Abdominal obesity · live BPL1",interventionType:"Live microorganism; distinct from BPL1-HT",effect:"A three-arm trial compared live CECT 8145, its heat-killed preparation, and placebo for three months.",outcome:"BMI, waist circumference, and visceral-fat area",metric:"1 × 10¹⁰ CFU/day; n=135",absolute:"Placebo contrasts differed between live and heat-killed preparations",nnt:"Not applicable",dose:"1 × 10¹⁰ CFU/day",doseDetail:"One capsule daily for three months. Live and heat-killed forms are recorded as separate interventions.",duration:"12 weeks",population:"Adults with abdominal obesity.",caveat:"Endpoints were anthropometric and do not establish fewer clinical events or obesity monotherapy.",studies:[{design:"Three-arm double-blind RCT",n:"135",year:"2019",result:"Lower BMI versus placebo was reported with the live form; other changes varied by preparation and sex.",limitation:"Multiple analyses, anthropometric outcomes, and declared industry ties.",url:"https://pubmed.ncbi.nlm.nih.gov/30262813/"}]}
    },
    {
      id:"lb-pediatric-acute-diarrhea", area:"Pediatría", genus:"Lactobacillus", species:"LB", strain:"CNCM I-2998 + CNCM I-4831 inactivadas", displayName:"Lactobacillus LB · CNCM I-2998 + CNCM I-4831 inactivadas", aliases:["Lactobacillus LB","CNCM I-2998","CNCM I-4831","Lacteol"], condition:"Diarrea aguda leve en niños", conditionShort:"Diarrea aguda · Lactobacillus LB", keywords:["pediatría","diarrea aguda","postbiótico"], intent:"Coadyuvante", ageGroup:"pediatric", mexicoAvailable:true, interventionType:"Microorganismos inactivados y medio fermentado; no es probiótico vivo",
      effect:"Un ensayo controlado evaluó la preparación Lactobacillus LB añadida a rehidratación y alimentación habituales.", outcome:"Tiempo hasta recuperación", metric:"Aproximadamente 1 día menos en diarrea no causada por rotavirus", absolute:"Diferencia concentrada en el subgrupo no rotavirus", nnt:"No publicado", dose:"Pauta del ensayo", doseDetail:"La intervención incluye dos microorganismos inactivados y componentes del medio fermentado; no debe dividirse por cepa.", duration:"Durante el episodio", population:"Niños con diarrea aguda leve.", caveat:"No sustituye rehidratación oral. El resultado por etiología fue un análisis de subgrupo.", studies:[{design:"ECA controlado",n:"80",year:"2007",result:"Menor tiempo de recuperación, aproximadamente un día, en el subgrupo con diarrea no causada por rotavirus.",limitation:"Muestra pequeña y resultado concentrado en un subgrupo etiológico.",url:"https://pubmed.ncbi.nlm.nih.gov/17460488/"}],
      en:{condition:"Mild acute diarrhea in children",conditionShort:"Acute diarrhea · Lactobacillus LB",interventionType:"Heat-killed microorganisms and fermented medium; not a live probiotic",effect:"A controlled trial evaluated Lactobacillus LB added to usual rehydration and feeding.",outcome:"Time to recovery",metric:"Approximately 1 day shorter in non-rotavirus diarrhea",absolute:"Difference concentrated in the non-rotavirus subgroup",nnt:"Not reported",dose:"Trial regimen",doseDetail:"The intervention includes two heat-killed microorganisms and fermented-medium components and should not be separated by strain.",duration:"During the episode",population:"Children with mild acute diarrhea.",caveat:"It does not replace oral rehydration. The etiologic result was a subgroup analysis.",studies:[{design:"Controlled RCT",n:"80",year:"2007",result:"Recovery was approximately one day shorter in the non-rotavirus diarrhea subgroup.",limitation:"Small sample and result concentrated in an etiologic subgroup.",url:"https://pubmed.ncbi.nlm.nih.gov/17460488/"}]}
    },
    {
      id:"lb-chronic-diarrhea", area:"Gastrointestinal", genus:"Lactobacillus", species:"LB", strain:"CNCM I-2998 + CNCM I-4831 inactivadas", displayName:"Lactobacillus LB · CNCM I-2998 + CNCM I-4831 inactivadas", aliases:["Lactobacillus LB","CNCM I-2998","CNCM I-4831","diarrea crónica"], condition:"Diarrea crónica", conditionShort:"Diarrea crónica · Lactobacillus LB", keywords:["diarrea crónica","frecuencia de evacuaciones","postbiótico"], intent:"Tratamiento", ageGroup:"adult", mexicoAvailable:true, interventionType:"Microorganismos inactivados y medio fermentado; no es probiótico vivo",
      effect:"Un ensayo multicéntrico comparó Lactobacillus LB inactivado con placebo durante cuatro semanas.", outcome:"Frecuencia diaria de evacuaciones", metric:"Semana 2: 1.88 vs 2.64 evacuaciones/día", absolute:"Semana 4: 1.39 vs 2.19 evacuaciones/día", nnt:"No publicado", dose:"Pauta del ensayo", doseDetail:"La preparación completa incluye microorganismos inactivados y medio fermentado.", duration:"4 semanas", population:"Adultos con diarrea crónica.", caveat:"La diarrea crónica requiere evaluación etiológica; esta ficha no sustituye el estudio de causas orgánicas, infecciosas o farmacológicas.", studies:[{design:"ECA multicéntrico",n:"137",year:"2003",result:"Menor frecuencia de evacuaciones en las semanas 2 y 4 frente a placebo.",limitation:"Ensayo antiguo y definición clínica dependiente del protocolo.",url:"https://pubmed.ncbi.nlm.nih.gov/14964345/"}],
      en:{condition:"Chronic diarrhea",conditionShort:"Chronic diarrhea · Lactobacillus LB",interventionType:"Heat-killed microorganisms and fermented medium; not a live probiotic",effect:"A multicenter trial compared heat-killed Lactobacillus LB with placebo for four weeks.",outcome:"Daily stool frequency",metric:"Week 2: 1.88 vs 2.64 stools/day",absolute:"Week 4: 1.39 vs 2.19 stools/day",nnt:"Not reported",dose:"Trial regimen",doseDetail:"The complete preparation includes heat-killed microorganisms and fermented-medium components.",duration:"4 weeks",population:"Adults with chronic diarrhea.",caveat:"Chronic diarrhea requires etiologic assessment; this record does not replace investigation of organic, infectious, or drug-related causes.",studies:[{design:"Multicenter RCT",n:"137",year:"2003",result:"Lower stool frequency was reported at weeks 2 and 4 versus placebo.",limitation:"Older trial with a protocol-dependent clinical definition.",url:"https://pubmed.ncbi.nlm.nih.gov/14964345/"}]}
    },
    {
      id:"kabp041-042-infant-colic", area:"Pediatría", genus:"Bifidobacterium longum + Pediococcus", species:"longum + pentosaceus", strain:"KABP-042 + KABP-041", displayName:"<i>Bifidobacterium longum</i> KABP-042 + <i>Pediococcus pentosaceus</i> KABP-041", aliases:["KABP-042","CECT 7894","KABP-041","CECT 8330","cólico"], condition:"Cólico del lactante", conditionShort:"Cólico del lactante · KABP", keywords:["pediatría","lactante","cólico","llanto"], intent:"Tratamiento", ageGroup:"pediatric", mexicoAvailable:true, interventionType:"Combinación inseparable de dos cepas",
      effect:"Un ensayo aleatorizado administró la combinación durante 21 días a lactantes con cólico por criterios Roma IV.", outcome:"Tiempo diario de llanto", metric:"Día 21: mediana 14 vs 40 min/día", absolute:"Día 7: 38 vs 62; día 14: 20 vs 50 min/día", nnt:"No publicado", dose:"1 × 10⁹ UFC/día", doseDetail:"Administración oral diaria de la combinación KABP-041 + KABP-042.", duration:"21 días", population:"Lactantes menores de dos meses, alimentados al pecho o con alimentación mixta.", caveat:"No extrapolar a una sola cepa, a fórmula exclusiva o a productos con componentes adicionales.", studies:[{design:"ECA doble ciego",n:"112 reclutados; 90 analizados",year:"2021",result:"Menor mediana de llanto en los días 7, 14 y 21 frente a placebo.",limitation:"Registro retrospectivo y población muy pequeña por edad.",url:"https://pubmed.ncbi.nlm.nih.gov/34568236/"},{design:"ECA comparativo",n:"Según publicación",year:"2024",result:"Mayor tasa de respuesta y mayor reducción del llanto con la combinación frente al comparador activo.",limitation:"Comparación entre intervenciones activas; revisar población y protocolo antes de extrapolar.",url:"https://pubmed.ncbi.nlm.nih.gov/39390276/"}],
      en:{condition:"Infant colic",conditionShort:"Infant colic · KABP",interventionType:"Inseparable two-strain combination",effect:"A randomized trial administered the combination for 21 days to infants meeting Rome IV colic criteria.",outcome:"Daily crying time",metric:"Day 21: median 14 vs 40 min/day",absolute:"Day 7: 38 vs 62; day 14: 20 vs 50 min/day",nnt:"Not reported",dose:"1 × 10⁹ CFU/day",doseDetail:"Daily oral administration of the KABP-041 + KABP-042 combination.",duration:"21 days",population:"Infants younger than two months who were breastfed or mixed-fed.",caveat:"Do not extrapolate to one strain, exclusive formula feeding, or products with additional components.",studies:[{design:"Double-blind RCT",n:"112 recruited; 90 analyzed",year:"2021",result:"Lower median crying time was reported on days 7, 14, and 21 versus placebo.",limitation:"Retrospective registration and a very young study population.",url:"https://pubmed.ncbi.nlm.nih.gov/34568236/"},{design:"Comparative RCT",n:"Per publication",year:"2024",result:"A higher response rate and larger crying-time reduction were reported for the combination versus the active comparator.",limitation:"Active-intervention comparison; population and protocol require review before transfer.",url:"https://pubmed.ncbi.nlm.nih.gov/39390276/"}]}
    },
    {
      id:"r0052-r0175-stress", area:"Salud mental", genus:"Lactobacillus helveticus + Bifidobacterium longum", species:"helveticus + longum", strain:"R0052 + R0175", displayName:"<i>Lactobacillus helveticus</i> R0052 + <i>Bifidobacterium longum</i> R0175", aliases:["R0052","R0175","R-52","R-175","estrés"], condition:"Malestar psicológico en adultos sanos", conditionShort:"Estrés · R0052/R0175", keywords:["estrés","ansiedad","malestar psicológico","cortisol"], intent:"Coadyuvante", ageGroup:"adult", mexicoAvailable:true, interventionType:"Combinación inseparable de dos cepas",
      effect:"Un ensayo de 30 días evaluó escalas psicológicas y cortisol urinario en voluntarios sanos.", outcome:"HSCL-90, HADS y cortisol urinario", metric:"Diferencias reportadas en subescalas; p<0.05", absolute:"Sin umbral clínico binario publicado", nnt:"No estimable", dose:"3 × 10⁹ UFC/día", doseDetail:"Administración diaria de la combinación R0052 + R0175 durante treinta días.", duration:"30 días", population:"Adultos sanos con distintos niveles de estrés basal.", caveat:"No equivale a tratamiento de ansiedad o depresión. Otros ensayos han usado poblaciones y desenlaces diferentes.", studies:[{design:"ECA doble ciego",n:"55",year:"2011",result:"Menores puntajes en dominios de HSCL-90 y menor cortisol urinario frente a placebo.",limitation:"Muestra pequeña, múltiples escalas y voluntarios sanos.",url:"https://pubmed.ncbi.nlm.nih.gov/20974015/"}],
      en:{condition:"Psychological distress in healthy adults",conditionShort:"Stress · R0052/R0175",interventionType:"Inseparable two-strain combination",effect:"A 30-day trial assessed psychological scales and urinary cortisol in healthy volunteers.",outcome:"HSCL-90, HADS, and urinary cortisol",metric:"Differences reported in subscales; p<0.05",absolute:"No binary clinical threshold was reported",nnt:"Not estimable",dose:"3 × 10⁹ CFU/day",doseDetail:"Daily administration of the R0052 + R0175 combination for thirty days.",duration:"30 days",population:"Healthy adults with different baseline stress levels.",caveat:"This is not treatment for anxiety or depression. Other trials have used different populations and outcomes.",studies:[{design:"Double-blind RCT",n:"55",year:"2011",result:"Lower scores in selected HSCL-90 domains and lower urinary cortisol were reported versus placebo.",limitation:"Small sample, multiple scales, and healthy volunteers.",url:"https://pubmed.ncbi.nlm.nih.gov/20974015/"}]}
    },
    {
      id:"lpc37-perceived-stress", area:"Salud mental", genus:"Lacticaseibacillus", species:"paracasei", strain:"Lpc-37", aliases:["Lpc-37","estrés percibido","Sisu"], condition:"Estrés percibido en adultos sanos", conditionShort:"Estrés percibido · Lpc-37", keywords:["estrés","ansiedad","cortisol","TSST"], intent:"Coadyuvante", ageGroup:"adult", mexicoAvailable:true, interventionType:"Microorganismo vivo",
      effect:"Un ensayo de cinco semanas evaluó respuesta cardiaca a estrés agudo, estrés percibido y otros desenlaces secundarios.", outcome:"Frecuencia cardiaca durante TSST y estrés percibido", metric:"Desenlace primario de frecuencia cardiaca sin diferencia", absolute:"Estrés percibido menor en análisis por protocolo; n=113", nnt:"No aplica", dose:"1.75 × 10¹⁰ UFC/día", doseDetail:"Una dosis diaria durante cinco semanas después de dos semanas de preinclusión.", duration:"5 semanas", population:"Adultos sanos de 18 a 45 años, estratificados por estrés crónico basal.", caveat:"La diferencia en estrés percibido fue secundaria y el desenlace primario no cambió; no corresponde a tratamiento de un trastorno de ansiedad.", studies:[{design:"ECA doble ciego",n:"120",year:"2020",result:"Menor estrés percibido en el análisis por protocolo; el desenlace primario no mostró diferencia.",limitation:"Resultado favorable secundario, subgrupos múltiples y patrocinio industrial.",url:"https://pubmed.ncbi.nlm.nih.gov/33385020/"}],
      en:{condition:"Perceived stress in healthy adults",conditionShort:"Perceived stress · Lpc-37",interventionType:"Live microorganism",effect:"A five-week trial assessed heart-rate response to acute stress, perceived stress, and other secondary outcomes.",outcome:"Heart rate during TSST and perceived stress",metric:"No difference in the primary heart-rate outcome",absolute:"Lower perceived stress in per-protocol analysis; n=113",nnt:"Not applicable",dose:"1.75 × 10¹⁰ CFU/day",doseDetail:"One daily dose for five weeks after a two-week run-in.",duration:"5 weeks",population:"Healthy adults aged 18–45 years, stratified by baseline chronic stress.",caveat:"Perceived stress was a secondary result and the primary outcome did not change; this is not treatment of an anxiety disorder.",studies:[{design:"Double-blind RCT",n:"120",year:"2020",result:"Lower perceived stress was reported in the per-protocol analysis; the primary outcome did not differ.",limitation:"Favorable secondary result, multiple subgroups, and industry sponsorship.",url:"https://pubmed.ncbi.nlm.nih.gov/33385020/"}]}
    },
    {
      id:"lcasei431-urti-duration", area:"Alergología e inmunología", genus:"Lacticaseibacillus", species:"paracasei", strain:"431", former:"También rotulada como Lactobacillus casei 431", aliases:["L. casei 431","L. paracasei 431","431","vacunación influenza"], condition:"Duración de síntomas respiratorios después de vacunación contra influenza", conditionShort:"Síntomas respiratorios · 431", keywords:["infección respiratoria","influenza","vacunación","resfriado"], intent:"Prevención", ageGroup:"adult", mexicoAvailable:true, interventionType:"Microorganismo vivo",
      effect:"Un ensayo evaluó respuesta inmunitaria a vacunación y episodios respiratorios durante el seguimiento.", outcome:"Respuesta a vacuna y duración de síntomas respiratorios", metric:"Sin diferencia en la respuesta inmunitaria a vacunación", absolute:"Menor duración de síntomas respiratorios reportada", nnt:"No publicado", dose:"Pauta diaria del ensayo", doseDetail:"La cepa se administró diariamente alrededor del periodo de vacunación; confirmar la matriz y dosis exactas en la publicación antes de trasladarlas.", duration:"Seguimiento alrededor de la vacunación", population:"Adultos sanos vacunados contra influenza.", caveat:"El resultado respiratorio no demuestra mayor respuesta a la vacuna ni tratamiento de influenza.", studies:[{design:"ECA doble ciego",n:"Adultos sanos",year:"2012",result:"Menor duración de síntomas respiratorios; la respuesta inmunitaria a vacunación no mostró diferencia.",limitation:"El desenlace inmunitario principal no cambió.",url:"https://researchprofiles.ku.dk/en/publications/effect-of-lactobacillus-paracasei-subsp-paracasei-l-casei-431-on/"}],
      en:{condition:"Respiratory-symptom duration after influenza vaccination",conditionShort:"Respiratory symptoms · 431",interventionType:"Live microorganism",effect:"A trial assessed vaccine immune response and respiratory episodes during follow-up.",outcome:"Vaccine response and respiratory-symptom duration",metric:"No difference in immune response to vaccination",absolute:"Shorter respiratory-symptom duration was reported",nnt:"Not reported",dose:"Daily trial regimen",doseDetail:"The strain was administered daily around vaccination; confirm the exact matrix and dose in the publication before transfer.",duration:"Follow-up around vaccination",population:"Healthy adults receiving influenza vaccination.",caveat:"The respiratory result does not establish a stronger vaccine response or treatment of influenza.",studies:[{design:"Double-blind RCT",n:"Healthy adults",year:"2012",result:"Shorter respiratory-symptom duration was reported; immune response to vaccination did not differ.",limitation:"The primary immune outcome did not change.",url:"https://researchprofiles.ku.dk/en/publications/effect-of-lactobacillus-paracasei-subsp-paracasei-l-casei-431-on/"}]}
    },
    {
      id:"la14-hn001-lactoferrin-bv", area:"Salud urogenital", genus:"Lactobacillus acidophilus + Lacticaseibacillus", species:"acidophilus + rhamnosus", strain:"La-14 + HN001 con lactoferrina", displayName:"<i>Lactobacillus acidophilus</i> La-14 + <i>Lacticaseibacillus rhamnosus</i> HN001 con lactoferrina", aliases:["La-14","HN001","lactoferrina","vaginosis bacteriana"], condition:"Vaginosis bacteriana recurrente como coadyuvante de metronidazol", conditionShort:"Vaginosis recurrente · coadyuvante", keywords:["vaginosis","microbiota vaginal","recurrencia","metronidazol"], intent:"Coadyuvante", ageGroup:"adult", mexicoAvailable:true, interventionType:"Combinación de dos cepas con 50 mg de lactoferrina",
      effect:"Un ensayo de seguimiento de seis meses añadió La-14 + HN001 + lactoferrina al tratamiento con metronidazol.", outcome:"Curación clínica/microbiológica y recurrencia", metric:"Diferencias reportadas en curación y recurrencia; p<0.05", absolute:"48 participantes", nnt:"No publicado", dose:"5–10 × 10⁹ UFC/día + 50 mg de lactoferrina", doseDetail:"Fase inicial de 10 × 10⁹ UFC/día durante cinco días, después 5 × 10⁹ UFC/día; mantenimiento mensual según el protocolo.", duration:"6 meses de seguimiento", population:"Mujeres adultas con vaginosis bacteriana sintomática recurrente tratadas con metronidazol.", caveat:"La lactoferrina y el esquema antimicrobiano forman parte de la intervención. La disponibilidad mexicana de las cepas no demuestra disponibilidad ni equivalencia de la formulación completa.", studies:[{design:"ECA doble ciego",n:"48",year:"2019",result:"Mayor curación global y menor recurrencia en varios puntos de seguimiento frente a placebo.",limitation:"Muestra pequeña; combinación inseparable con lactoferrina y metronidazol.",url:"https://hcp.howaru.com/howaru-benefit-areas/womens-health/vaginal-health/"}],
      en:{condition:"Recurrent bacterial vaginosis as an adjunct to metronidazole",conditionShort:"Recurrent vaginosis · adjunct",interventionType:"Two-strain combination with 50 mg lactoferrin",effect:"A six-month trial added La-14 + HN001 + lactoferrin to metronidazole treatment.",outcome:"Clinical/microbiological cure and recurrence",metric:"Differences in cure and recurrence were reported; p<0.05",absolute:"48 participants",nnt:"Not reported",dose:"5–10 × 10⁹ CFU/day + 50 mg lactoferrin",doseDetail:"Initial 10 × 10⁹ CFU/day for five days, followed by 5 × 10⁹ CFU/day and monthly maintenance according to protocol.",duration:"6-month follow-up",population:"Adult women with symptomatic recurrent bacterial vaginosis treated with metronidazole.",caveat:"Lactoferrin and antimicrobial therapy are part of the intervention. Mexican availability of the strains does not establish availability or equivalence of the complete formulation.",studies:[{design:"Double-blind RCT",n:"48",year:"2019",result:"Higher overall cure and lower recurrence were reported at several follow-up points versus placebo.",limitation:"Small sample; inseparable combination with lactoferrin and metronidazole.",url:"https://hcp.howaru.com/howaru-benefit-areas/womens-health/vaginal-health/"}]}
    }
  ];
  window.PROBIOCLIN_V3 = [...(window.PROBIOCLIN_V3 || []), ...records];
})();
